// src/ontologyMatcher.js

// --- PASTE RESULTS FROM YOUR RESEARCH AI HERE ---
const keywordMap = {
  // ============= CORROSION & PROTECTION =============
  'rust': ['corrosion'],
  'corrosion': ['corrosion'],
  'oxidation': ['corrosion'],
  'oxidize': ['corrosion'],
  'corrode': ['corrosion'],
  'rustproof': ['corrosion'],
  'antirust': ['corrosion'],
  'anticorrosion': ['corrosion'],
  'tarnish': ['corrosion'],
  'patina': ['corrosion'],
  'galvanic': ['corrosion'],
  'cathodic': ['corrosion'],
  'anodic': ['corrosion'],
  'passivation': ['corrosion', 'coating'],
  'weathering': ['corrosion', 'barrier'],
  'degradation': ['corrosion', 'wear'],
  'degrade': ['corrosion'],
  'pitting': ['corrosion'],
  'crevice': ['corrosion'],
  'intergranular': ['corrosion'],
  'protect': ['corrosion', 'barrier'],
  'resistance': ['corrosion', 'wear', 'electrical'],
  
  // ============= ELECTRICAL & CONDUCTIVITY =============
  'conduct': ['conductivity', 'conductive', 'electrical'],
  'conductive': ['conductive', 'conductivity', 'electrical'],
  'conductivity': ['conductivity', 'electrical'],
  'conductor': ['conductivity', 'electrical'],
  'electrical': ['electrical'],
  'electron': ['conductive', 'electrical'],
  'mobility': ['conductive', 'electrical'],
  'superconducting': ['conductive', 'electrical', 'quantum'],
  'superconductor': ['conductive', 'electrical', 'quantum'],
  'resistive': ['electrical'],
  'resistivity': ['electrical'],
  'ohmic': ['electrical'],
  'static': ['electrical', 'conductivity'],
  'esd': ['electrical'],
  'electrostatic': ['electrical'],
  'antistatic': ['electrical'],
  'emi': ['electrical', 'shielding'],
  'electromagnetic': ['electrical', 'radiation'],
  'rfi': ['electrical', 'shielding'],
  'faraday': ['electrical', 'shielding'],
  'grounding': ['electrical'],
  'discharge': ['electrical'],
  'dielectric': ['electrical', 'insulation'],
  'capacitive': ['electrical', 'energy'],
  'impedance': ['electrical'],
  'current': ['electrical'],
  'voltage': ['electrical'],
  'piezoelectric': ['electrical', 'sensor', 'actuator'],
  'piezo': ['actuator', 'sensor', 'electrical'],
  'triboelectric': ['electrical'],
  'semiconductor': ['electrical'],
  'percolation': ['electrical', 'conductivity'],
  'tunneling': ['electrical', 'quantum'],
  'junction': ['electrical'],
  'ambipolar': ['electrical'],
  'ballistic': ['conductive', 'electrical'],
  'doping': ['electrical', 'additive'],
  'carrier': ['electrical'],
  'semimetal': ['electrical'],
  'minimumconductivity': ['conductivity'],
  'magnetoresistance': ['electrical'],
  'kineticinductance': ['electrical'],
  'permittivity': ['electrical'],
  'bipolar': ['electrical'],
  'band': ['electrical'],
  'conductionband': ['electrical'],
  'valenceband': ['electrical'],
  'dispersion': ['electrical'],
  'fet': ['electrical'],
  'hysteresis': ['electrical'],
  'backscattering': ['electrical'],
  'ballisticconductance': ['conductive'],
  'transistor': ['electrical'],
  'supertransistor': ['electrical'],
  'photoconductivity': ['conductive', 'optical'],
  'circuit': ['electrical'],
  'inductor': ['electrical'],
  'cmos': ['electrical'],
  'kubo': ['electrical'],
  'dyadic': ['electrical'],
  'greenfunction': ['electrical'],
  'transport': ['conductivity'],
  'zero-gap': ['electrical'],
  'analog': ['electrical'],
  'blockchain': ['electrical'],
  'chip': ['electrical'],
  
  // ============= THERMAL PROPERTIES =============
  'thermal': ['thermal'],
  'heat': ['thermal', 'heat'],
  'temperature': ['thermal'],
  'cooling': ['thermal'],
  'cool': ['thermal'],
  'heating': ['thermal', 'heat'],
  'dissipation': ['thermal', 'heat', 'conductivity'],
  'dissipate': ['thermal', 'conductivity'],
  'conduction': ['thermal', 'conductivity'],
  'sink': ['thermal'],
  'heatsink': ['thermal', 'conductivity'],
  'thermally': ['thermal'],
  'isothermal': ['thermal'],
  'adiabatic': ['thermal', 'insulation'],
  'convection': ['thermal'],
  'radiation': ['thermal', 'radiation'],
  'emissivity': ['thermal', 'coating'],
  'reflectivity': ['thermal', 'coating'],
  'cryogenic': ['thermal'],
  'pyrolytic': ['thermal'],
  'thermoelectric': ['thermal', 'electrical', 'energy'],
  'phase-change': ['thermal', 'smart'],
  'pcm': ['thermal', 'smart'],
  'melting': ['thermal'],
  'freezing': ['thermal'],
  'expansion': ['thermal', 'mechanical'],
  'thermalexpansion': ['thermal'],
  'contraction': ['thermal', 'mechanical'],
  'gradient': ['thermal'],
  'flux': ['thermal'],
  'transfer': ['thermal'],
  'seebeck': ['thermal'],
  'phonondominated': ['thermal'],
  'wiedemannfranz': ['thermal'],
  'gruneisen': ['thermal'],
  'isotopic': ['thermal'],
  'thermalmanagement': ['thermal'],
  'tim': ['thermal'],
  'fourphonon': ['thermal'],
  'thermodynamic': ['thermal'],
  'photothermal': ['thermal', 'optical'],
  
  // ============= INSULATION =============
  'insulate': ['insulation'],
  'insulation': ['insulation'],
  'thermalinsulation': ['insulation', 'thermal'],
  'electricalinsulation': ['insulation', 'electrical'],
  'insulator': ['insulation'],
  'highk': ['insulation'],
  
  // ============= MECHANICAL PROPERTIES =============
  'mechanical': ['mechanical'],
  'strength': ['mechanical', 'strength'],
  'strong': ['mechanical', 'strength'],
  'strengthen': ['mechanical', 'strength'],
  'reinforcement': ['mechanical', 'strength'],
  'reinforce': ['mechanical', 'strength'],
  'reinforced': ['composite', 'strength'],
  'tensile': ['mechanical', 'strength'],
  'compressive': ['mechanical', 'strength'],
  'flexural': ['mechanical', 'strength'],
  'shear': ['mechanical'],
  'modulus': ['mechanical', 'strength'],
  'stiffness': ['mechanical', 'strength'],
  'stiff': ['mechanical'],
  'rigid': ['mechanical'],
  'elastic': ['mechanical', 'strength', 'flexible'],
  'plastic': ['mechanical'],
  'yield': ['mechanical'],
  'fracture': ['mechanical', 'strength'],
  'toughness': ['mechanical', 'strength'],
  'tough': ['mechanical', 'strength'],
  'hardness': ['mechanical', 'strength'],
  'hard': ['mechanical'],
  'soft': ['mechanical', 'flexible'],
  'ductile': ['mechanical'],
  'ductility': ['mechanical'],
  'brittle': ['mechanical'],
  'fatigue': ['mechanical', 'wear'],
  'creep': ['mechanical'],
  'impact': ['mechanical', 'strength'],
  'resilient': ['mechanical', 'strength'],
  'resilience': ['mechanical', 'strength'],
  'deformation': ['mechanical'],
  'strain': ['mechanical', 'sensor'],
  'stress': ['mechanical'],
  'load': ['mechanical'],
  'bearing': ['mechanical', 'wear'],
  'durability': ['mechanical', 'strength', 'wear'],
  'young': ['mechanical'],
  'intrinsic': ['strength'],
  'engineering': ['strength'],
  'springconstant': ['mechanical'],
  'poisson': ['mechanical'],
  'auxetic': ['mechanical'],
  'pseudo': ['mechanical'],
  'rippling': ['mechanical'],
  'inertial': ['mechanical'],
  'electromechanical': ['mechanical', 'electrical'],
  'dynamics': ['mechanical'],
  'negativepoisson': ['mechanical'],
  'tilt': ['mechanical'],
  'disclination': ['mechanical'],
  'anomalousstrength': ['strength'],
  'weakening': ['mechanical'],
  'highstrength': ['strength'],
  'robust': ['strength'],
  'crystallinity': ['mechanical'],
  
  // ============= WEAR & TRIBOLOGY =============
  'wear': ['wear', 'abrasion'],
  'abrasion': ['wear', 'abrasion'],
  'abrasive': ['wear', 'abrasion'],
  'abrade': ['abrasion'],
  'friction': ['friction', 'wear'],
  'antifriction': ['friction'],
  'tribology': ['friction', 'wear', 'lubrication'],
  'lubrication': ['lubrication', 'friction'],
  'lubricant': ['lubrication', 'friction'],
  'lubricate': ['lubrication'],
  'lubricious': ['lubrication', 'friction'],
  'slip': ['friction', 'lubrication'],
  'sliding': ['friction', 'lubrication'],
  'turbostratic': ['friction', 'lubrication', 'conductivity'],
  'scratch': ['wear', 'abrasion'],
  'erosion': ['wear', 'abrasion'],
  'durable': ['wear', 'mechanical'],
  'lasting': ['wear', 'mechanical'],
  'resistant': ['wear', 'abrasion'],
  'coefficient': ['friction'],
  'stick-slip': ['friction'],
  'galling': ['wear', 'friction'],
  'seizure': ['wear', 'friction'],
  'scuffing': ['wear', 'friction'],
  'oil': ['lubrication'],
  
  // ============= BARRIER & PERMEABILITY =============
  'barrier': ['barrier'],
  'permeability': ['barrier', 'permeability'],
  'permeable': ['permeability'],
  'impermeable': ['barrier', 'permeability'],
  'seal': ['barrier', 'sealing'],
  'sealing': ['barrier', 'sealing'],
  'gasket': ['barrier', 'sealing'],
  'o-ring': ['barrier', 'sealing'],
  'hermetic': ['barrier', 'sealing'],
  'leak': ['barrier'],
  'leakage': ['barrier'],
  'diffusion': ['barrier', 'permeability'],
  'permeation': ['barrier', 'permeability'],
  'migration': ['barrier'],
  'moisture': ['barrier', 'permeability', 'hydrophobic'],
  'water': ['barrier', 'hydrophobic', 'hydrophilic'],
  'vapor': ['barrier'],
  'gas': ['barrier', 'separation'],
  'liquid': ['barrier'],
  'oxygen': ['barrier'],
  'nitrogen': ['barrier'],
  'hydrogen': ['barrier', 'energy', 'storage'],
  'helium': ['barrier'],
  'co2': ['barrier', 'separation'],
  'voc': ['barrier', 'filter', 'environmental'],
  'protection': ['barrier'],
  'waterproof': ['barrier', 'hydrophobic'],
  'packaging': ['barrier', 'coating'],
  'barrierfilm': ['barrier', 'film'],
  
  // ============= COATINGS & SURFACE =============
  'coating': ['coating', 'surface'],
  'coat': ['coating', 'surface'],
  'surface': ['coating', 'surface'],
  'paint': ['coating', 'surface', 'paint'],
  'film': ['coating', 'film'],
  'thinfilm': ['film'],
  'layer': ['coating'],
  'deposition': ['coating'],
  'deposit': ['coating'],
  'spray': ['coating'],
  'dip': ['coating'],
  'spin': ['coating'],
  'cvd': ['coating'],
  'pvd': ['coating'],
  'plating': ['coating'],
  'anodizing': ['coating', 'corrosion'],
  'galvanizing': ['coating', 'corrosion'],
  'primer': ['coating'],
  'topcoat': ['coating'],
  'basecoat': ['coating'],
  'clearcoat': ['coating'],
  'varnish': ['coating'],
  'lacquer': ['coating'],
  'enamel': ['coating'],
  'powder': ['coating'],
  'thick-film': ['coating', 'film'],
  'conformal': ['coating'],
  'encapsulation': ['coating', 'barrier'],
  'nanocoating': ['coating'],
  'edge': ['surface'],
  'defect': ['surface'],
  'specificsurfacearea': ['surface'],
  'functionalgroup': ['surface'],
  'carboxyl': ['surface'],
  'amide': ['surface'],
  'hydrogenation': ['surface'],
  'fluorination': ['surface'],
  'selfrepair': ['surface', 'smart'],
  'functionalized': ['surface'],
  'printed': ['coating'],
  'rolltoroll': ['coating'],
  'printer': ['coating'],
  'ink': ['coating'],
  'atomiclayer': ['film'],
  'singlelayer': ['film'],
  
  // ============= ADDITIVES & COMPOSITES =============
  'additive': ['additive'],
  'admixture': ['additive', 'admixture'],
  'filler': ['additive', 'filler'],
  'composite': ['composite'],
  'compound': ['compound', 'composite'],
  'blend': ['composite'],
  'mix': ['additive', 'composite'],
  'mixture': ['additive', 'composite'],
  'dispersion': ['additive'],
  'suspension': ['additive'],
  'colloid': ['additive'],
  'masterbatch': ['additive', 'compound'],
  'concentrate': ['additive'],
  'loading': ['additive'],
  'dopant': ['additive'],
  'matrix': ['composite'],
  'reinforcing': ['composite', 'mechanical'],
  'fiber': ['composite'],
  'laminate': ['composite'],
  'sandwich': ['composite'],
  'hybrid': ['composite'],
  'nanocomposite': ['composite'],
  'fractal': ['composite', 'hierarchical'],
  'allotrope': ['compound'],
  'intercalation': ['compound'],
  'grapheneoxide': ['compound'],
  'graphane': ['compound'],
  'fluorographene': ['compound'],
  'graphite': ['compound'],
  'gfns': ['compound'],
  'nanoplatelet': ['additive'],
  'nanofluid': ['fluid', 'additive'],
  'functionalfluid': ['compound'],
  'microsphere': ['additive'],
  'heterostructure': ['compound'],
  'carbonnanotube': ['compound'],
  'nanotube': ['compound'],
  'silk': ['composite'],
  'cement': ['composite', 'strength'],
  'nickelgraphene': ['composite'],
  'lightweightcomposite': ['composite', 'lightweight'],
  'textile': ['composite'],
  '3dprinter': ['additive'],
  
  // ============= SENSORS & DETECTION =============
  'sensor': ['sensor', 'sensing'],
  'sensing': ['sensor', 'sensing'],
  'detect': ['sensor', 'detection'],
  'detection': ['sensor', 'detection'],
  'detector': ['sensor', 'detection'],
  'monitor': ['sensor', 'monitoring'],
  'monitoring': ['sensor', 'monitoring'],
  'gauge': ['sensor'],
  'transducer': ['sensor', 'actuator'],
  'probe': ['sensor'],
  'biosensor': ['sensor', 'biocompatible', 'medical'],
  'chemosensor': ['sensor'],
  'chemicalsensor': ['sensor'],
  'photosensor': ['sensor', 'optical'],
  'opticalsensor': ['sensor', 'optical'],
  'thermistor': ['sensor', 'thermal'],
  'thermocouple': ['sensor', 'thermal'],
  'strain-gauge': ['sensor', 'mechanical'],
  'accelerometer': ['sensor', 'mechanical'],
  'gyroscope': ['sensor'],
  'magnetometer': ['sensor'],
  'proximity': ['sensor'],
  'pressure': ['sensor', 'mechanical'],
  'flow': ['sensor'],
  'level': ['sensor'],
  'humidity': ['sensor'],
  'gas-sensor': ['sensor'],
  'gassensor': ['sensor'],
  'piezoresistive': ['sensor', 'mechanical', 'electrical'],
  'uvsensor': ['sensor', 'radiation'],
  'photoresponsivity': ['sensor', 'optical'],
  'receptor': ['sensing'],
  'selectivity': ['sensing', 'catalyst'],
  'nems': ['sensor'],
  'touchpanel': ['sensor'],
  'touchscreen': ['transparent', 'sensor'],
  'wearablesensor': ['sensor', 'flexible'],
  'gasdetection': ['detection'],
  'chemicaldetection': ['detection'],
  'metrology': ['monitoring'],
  'crop': ['sensor'],
  'tattoo': ['sensor', 'flexible'],
  
  // ============= FILTRATION & SEPARATION =============
  'filter': ['filter', 'filtration'],
  'filtration': ['filter', 'filtration'],
  'membrane': ['membrane', 'separation'],
  'separation': ['separation'],
  'purification': ['purification', 'filter'],
  'purify': ['purification', 'filter'],
  'sieve': ['filter', 'separation'],
  'screen': ['filter'],
  'mesh': ['filter'],
  'porous': ['filter', 'membrane'],
  'porosity': ['filter', 'membrane'],
  'pore': ['filter', 'membrane'],
  'adsorption': ['adsorption', 'filter'],
  'adsorb': ['adsorption', 'filter'],
  'absorption': ['absorption', 'optical'],
  'absorb': ['absorption'],
  'desorption': ['adsorption'],
  'sorption': ['adsorption', 'absorption'],
  'sorbent': ['adsorption'],
  'adsorbent': ['adsorption'],
  'chromatography': ['separation'],
  'distillation': ['separation', 'purification'],
  'osmosis': ['membrane', 'separation'],
  'reverse-osmosis': ['membrane', 'separation'],
  'ro': ['membrane', 'separation'],
  'ultrafiltration': ['membrane', 'separation'],
  'uf': ['membrane', 'separation'],
  'nanofiltration': ['membrane', 'separation'],
  'nf': ['membrane', 'separation'],
  'microfiltration': ['membrane', 'separation'],
  'mf': ['membrane', 'separation'],
  'dialysis': ['membrane', 'separation', 'medical', 'filtration'],
  'pervaporation': ['membrane', 'separation'],
  'desalination': ['membrane', 'separation', 'filtration'],
  'ion-exchange': ['separation'],
  'waterpurification': ['purification'],
  'gasseparation': ['separation'],
  'proton': ['membrane', 'fuel cell'],
  'iontransport': ['membrane'],
  
  // ============= CATALYSIS =============
  'catalyst': ['catalyst', 'catalysis'],
  'catalysis': ['catalyst', 'catalysis'],
  'catalytic': ['catalyst', 'catalysis'],
  'catalyze': ['catalyst', 'catalysis'],
  'electrocatalyst': ['catalyst', 'electrical'],
  'photocatalyst': ['catalyst', 'optical'],
  'biocatalyst': ['catalyst', 'bio', 'medical'],
  'enzyme': ['catalyst', 'bio'],
  'cocatalyst': ['catalyst'],
  'promoter': ['catalyst'],
  'substrate': ['catalyst'],
  'active-site': ['catalyst'],
  'turnover': ['catalyst'],
  'conversion': ['catalyst'],
  'reduction': ['catalyst'],
  'oxidation': ['catalyst', 'corrosion'],
  'hydrogenation': ['catalyst', 'surface'],
  'dehydrogenation': ['catalyst'],
  'reforming': ['catalyst'],
  'cracking': ['catalyst'],
  'reactivity': ['catalyst'],
  'catalyticcell': ['catalyst'],
  
  // ============= ENERGY STORAGE & CONVERSION =============
  'energy': ['energy'],
  'storage': ['storage', 'energy'],
  'battery': ['battery', 'energy', 'storage'],
  'capacitor': ['capacitor', 'energy', 'storage'],
  'supercapacitor': ['capacitor', 'energy', 'storage'],
  'ultracapacitor': ['capacitor', 'energy', 'storage'],
  'electrode': ['battery', 'electrical'],
  'anode': ['battery', 'electrical'],
  'cathode': ['battery', 'electrical'],
  'electrolyte': ['battery'],
  'separator': ['battery', 'membrane'],
  'lithium': ['battery', 'doping'],
  'lithium-ion': ['battery'],
  'liion': ['battery'],
  'li-ion': ['battery'],
  'sodium': ['battery'],
  'sodium-ion': ['battery'],
  'solid-state': ['battery'],
  'fuel-cell': ['energy', 'catalyst'],
  'fuelcell': ['energy', 'catalyst', 'fuel cell'],
  'solar': ['energy', 'optical', 'solar'],
  'photovoltaic': ['energy', 'optical', 'solar'],
  'pv': ['energy', 'optical'],
  'wind': ['energy'],
  'turbine': ['energy', 'mechanical'],
  'generator': ['energy', 'electrical'],
  'inverter': ['energy', 'electrical'],
  'charge': ['energy', 'electrical'],
  'discharge': ['energy', 'electrical'],
  'cycle': ['energy', 'battery'],
  'capacity': ['energy', 'storage'],
  'power': ['energy', 'electrical'],
  'efficiency': ['energy'],
  'rechargeable': ['battery', 'storage'],
  'hydrogenstorage': ['storage'],
  'harddrive': ['storage'],
  'memory': ['storage'],
  'potassium': ['doping'],
  
  // ============= WEIGHT & DENSITY =============
  'lightweight': ['lightweight'],
  'light': ['lightweight'],
  'weight': ['lightweight'],
  'density': ['density', 'lightweight'],
  'lowdensity': ['density'],
  'dense': ['density'],
  'heavy': ['density'],
  'mass': ['density'],
  'specific-gravity': ['density'],
  'bulk': ['density'],
  'foam': ['lightweight', 'insulation'],
  'aerogel': ['lightweight', 'insulation'],
  'honeycomb': ['lightweight', 'mechanical'],
  'honeycomblattice': ['structure'],
  'hollow': ['lightweight'],
  
  // ============= FLEXIBILITY =============
  'flexible': ['flexible'],
  'flexibility': ['flexible'],
  'flex': ['flexible'],
  'bendable': ['flexible', 'bendable'],
  'bend': ['flexible', 'bendable'],
  'foldable': ['flexible'],
  'stretchable': ['flexible'],
  'stretch': ['flexible'],
  'elasticity': ['flexible'],
  'elastomer': ['flexible'],
  'rubber': ['flexible'],
  'compliant': ['flexible'],
  'conformable': ['flexible'],
  'deformable': ['flexible', 'mechanical'],
  'pliable': ['flexible'],
  'supple': ['flexible'],
  'malleable': ['flexible'],
  'crumpled': ['flexible'],
  'etextile': ['flexible'],
  'wearable': ['flexible', 'sensor'],
  
  // ============= OPTICAL & TRANSPARENCY =============
  'transparent': ['transparent', 'optical'],
  'transparency': ['transparent', 'optical'],
  'optical': ['optical'],
  'optic': ['optical'],
  'light': ['optical', 'lightweight'],
  'photonic': ['optical', 'quantum', 'photonic'],
  'photonics': ['photonic'],
  'optoelectronic': ['optical', 'electrical'],
  'optoelectronics': ['optical', 'electrical'],
  'transmittance': ['optical', 'transparent'],
  'transmission': ['optical'],
  'reflectance': ['optical'],
  'reflection': ['optical'],
  'refraction': ['optical'],
  'refractive': ['optical'],
  'refractiveindex': ['optical'],
  'scattering': ['optical'],
  'diffraction': ['optical'],
  'interference': ['optical'],
  'polarization': ['optical'],
  'birefringence': ['optical'],
  'luminescence': ['optical'],
  'fluorescence': ['optical'],
  'phosphorescence': ['optical'],
  'uv': ['optical', 'radiation'],
  'ultraviolet': ['optical', 'radiation'],
  'infrared': ['optical', 'thermal', 'radiation'],
  'ir': ['optical', 'thermal'],
  'visible': ['optical'],
  'visual': ['optical'],
  'laser': ['optical'],
  'led': ['optical', 'electrical'],
  'oled': ['optical', 'electrical'],
  'display': ['optical', 'electrical'],
  'screen': ['optical', 'filter'],
  'lens': ['optical'],
  'waveguide': ['optical'],
  'fiber-optic': ['optical'],
  'photonic-crystal': ['optical', 'quantum'],
  'photoniccrystal': ['photonic'],
  'transparentconductor': ['transparent', 'conductive'],
  'ito': ['transparent', 'conductive'],
  'saturableabsorption': ['absorption'],
  'nonlinear': ['optical'],
  'kerr': ['optical'],
  'tunable': ['optical'],
  'electrochromic': ['optical'],
  'bragggrating': ['optical'],
  'surfaceplasmon': ['optical'],
  'plasmon': ['optical'],
  'extinctioncoefficient': ['optical'],
  'fresnel': ['optical'],
  'conical': ['optical'],
  'ultrafastphotonics': ['photonic'],
  'modelocking': ['photonic'],
  'soliton': ['photonic'],
  'exciton': ['optical'],
  'polariton': ['photonic'],
  'excitonic': ['optical'],
  'smartwindow': ['optical'],
  'opticalcommunication': ['optical'],
  'photography': ['optical'],
  'absorber': ['absorption'],
  
  // ============= BIOMEDICAL =============
  'biocompatible': ['biocompatible', 'medical'],
  'biocompatibility': ['biocompatible', 'medical'],
  'medical': ['medical'],
  'biomedical': ['medical'],
  'implant': ['implant', 'medical'],
  'implantable': ['implant', 'medical'],
  'scaffold': ['scaffold', 'medical'],
  'tissue': ['medical', 'scaffold'],
  'tissueengineering': ['medical', 'scaffold'],
  'cell': ['medical'],
  'cellular': ['medical'],
  'drug': ['medical', 'delivery'],
  'delivery': ['delivery', 'medical'],
  'drugdelivery': ['delivery', 'medical'],
  'pharmaceutical': ['medical'],
  'therapeutic': ['medical'],
  'diagnostic': ['medical', 'sensor'],
  'antibacterial': ['medical', 'antimicrobial', 'biocompatible'],
  'antimicrobial': ['antimicrobial', 'medical', 'biocompatible'],
  'antiviral': ['medical', 'antimicrobial'],
  'antifungal': ['medical', 'antimicrobial'],
  'bactericide': ['biocompatible'],
  'sterile': ['medical'],
  'sterilization': ['medical'],
  'prosthetic': ['medical', 'implant'],
  'orthopedic': ['medical'],
  'dental': ['medical'],
  'surgical': ['medical'],
  'wound': ['medical'],
  'healing': ['medical'],
  'regenerative': ['medical'],
  'stem-cell': ['medical'],
  'stemcell': ['medical'],
  'gene': ['medical', 'delivery'],
  'protein': ['medical'],
  'peptide': ['medical'],
  'biochip': ['medical', 'sensor'],
  'lab-on-chip': ['medical', 'sensor'],
  'osteogenic': ['medical', 'implant'],
  'osteogenicdifferentiation': ['medical'],
  'neural': ['medical'],
  'neuralinteraction': ['medical'],
  'neurodegenerative': ['medical'],
  'braincomputer': ['medical'],
  'hydroxyapatite': ['implant'],
  'chitosan': ['biocompatible'],
  'osteoblast': ['medical'],
  'mesenchymal': ['medical'],
  'chemotherapy': ['delivery', 'medical'],
  'tumor': ['medical'],
  'cancer': ['medical'],
  'cancerbiomarker': ['detection', 'medical'],
  'dna': ['detection', 'medical'],
  'diabetes': ['monitoring', 'medical'],
  'epilepsy': ['medical'],
  'hiv': ['detection'],
  'antigen': ['detection'],
  'atp': ['detection'],
  'dopamine': ['detection'],
  'thrombin': ['detection'],
  'virus': ['detection'],
  'fungus': ['detection'],
  'condom': ['biocompatible'],
  'deafmute': ['acoustic', 'medical'],
  'signlanguage': ['acoustic', 'medical'],
  'bodyscan': ['medical', 'optical'],
  'biological': ['medical'],
  'toxicity': ['biocompatible'],
  'biomarker': ['detection', 'medical'],
  'dnasequencing': ['detection', 'medical'],
  
  // ============= ACOUSTIC PROPERTIES =============
  'acoustic': ['acoustic', 'sound'],
  'sound': ['acoustic', 'sound'],
  'audio': ['acoustic', 'sound'],
  'noise': ['acoustic'],
  'vibration': ['vibration', 'acoustic'],
  'damping': ['dampening', 'acoustic', 'mechanical'],
  'dampening': ['dampening', 'acoustic'],
  'attenuation': ['acoustic', 'dampening', 'radiation'],
  'insulation': ['acoustic', 'insulation'],
  'soundproofing': ['acoustic', 'insulation'],
  'resonance': ['acoustic', 'vibration'],
  'frequency': ['acoustic'],
  'ultrasonic': ['acoustic'],
  'infrasonic': ['acoustic'],
  'decibel': ['acoustic'],
  'echo': ['acoustic'],
  'reverberation': ['acoustic'],
  'acousticmode': ['acoustic'],
  'la': ['acoustic'],
  'ta': ['acoustic'],
  'za': ['acoustic'],
  'speaker': ['acoustic'],
  'headphone': ['acoustic'],
  
  // ============= WETTING PROPERTIES =============
  'hydrophobic': ['hydrophobic'],
  'hydrophilic': ['hydrophilic'],
  'wetting': ['wetting'],
  'wettability': ['wetting'],
  'contact-angle': ['wetting'],
  'superhydrophobic': ['hydrophobic'],
  'superhydrophilic': ['hydrophilic'],
  'oleophobic': ['hydrophobic'],
  'oleophilic': ['hydrophilic'],
  'amphiphobic': ['hydrophobic'],
  'amphiphilic': ['hydrophilic', 'hydrophobic'],
  'surfactant': ['wetting'],
  'anti-fog': ['hydrophilic', 'coating'],
  'antifog': ['anti-fog', 'hydrophilic'],
  'anti-icing': ['hydrophobic', 'coating'],
  'self-cleaning': ['hydrophobic', 'coating'],
  'lotus': ['hydrophobic'],
  'hydrophobicity': ['hydrophobic'],
  
  // ============= FIRE & FLAME RESISTANCE =============
  'flame': ['flame', 'fire', 'retardant'],
  'fire': ['fire', 'flame', 'retardant'],
  'retardant': ['retardant', 'fire'],
  'flame-retardant': ['retardant', 'fire'],
  'flameretardant': ['flame', 'retardant'],
  'fireretardant': ['fire', 'retardant'],
  'fireproof': ['fire', 'retardant'],
  'fire-resistant': ['fire', 'retardant'],
  'intumescent': ['fire', 'coating'],
  'char': ['fire'],
  'smoke': ['fire'],
  'combustion': ['fire'],
  'flammability': ['fire'],
  'ignition': ['fire'],
  'self-extinguishing': ['fire', 'retardant'],
  'ul94': ['fire', 'retardant'],
  
  // ============= RADIATION =============
  'radiation': ['radiation'],
  'shielding': ['shielding', 'radiation', 'electrical'],
  'shield': ['electrical', 'barrier', 'radiation'],
  'x-ray': ['radiation'],
  'gamma': ['radiation'],
  'neutron': ['radiation'],
  'alpha': ['radiation'],
  'beta': ['radiation'],
  'radiofrequency': ['radiation', 'electrical'],
  'rf': ['radiation', 'electrical'],
  'microwave': ['radiation', 'thermal'],
  'ionizing': ['radiation'],
  'non-ionizing': ['radiation'],
  'dosimetry': ['radiation', 'sensor'],
  'nuclear': ['radiation'],
  'thz': ['radiation'],
  'terahertz': ['radiation'],
  
  // ============= ADHESION & BONDING =============
  'adhesive': ['adhesive', 'bonding'],
  'adhesion': ['adhesive', 'bonding'],
  'bonding': ['bonding', 'adhesive'],
  'bond': ['bonding'],
  'glue': ['adhesive'],
  'epoxy': ['adhesive', 'coating'],
  'resin': ['adhesive', 'composite'],
  'sealant': ['adhesive', 'sealing'],
  'caulk': ['adhesive', 'sealing'],
  'tape': ['adhesive'],
  'psa': ['adhesive'],
  'pressure-sensitive': ['adhesive'],
  'structural': ['adhesive', 'mechanical'],
  'cure': ['adhesive'],
  'curing': ['adhesive'],
  'crosslink': ['adhesive', 'polymer'],
  'tack': ['adhesive'],
  'peel': ['adhesive', 'mechanical'],
  'cohesion': ['adhesive'],
  'vanderwaals': ['bonding'],
  'sp2': ['bonding'],
  'bondlength': ['bonding'],
  
  // ============= QUANTUM & ADVANCED =============
  'quantum': ['quantum'],
  'quantumhall': ['quantum'],
  'spintronic': ['quantum', 'spintronic'],
  'spintronics': ['spintronic'],
  'spin': ['quantum', 'spintronic'],
  'topological': ['quantum'],
  'hall': ['quantum', 'electrical'],
  'coherence': ['quantum'],
  'entanglement': ['quantum'],
  'qubit': ['quantum'],
  'josephson': ['quantum', 'electrical'],
  'metamaterial': ['quantum', 'optical', 'acoustic'],
  'magnon': ['quantum'],
  'phonon': ['quantum', 'thermal', 'acoustic'],
  '2d': ['quantum'],
  'two-dimensional': ['quantum'],
  'van-der-waals': ['quantum'],
  'moire': ['quantum'],
  'diracpoint': ['quantum'],
  'diracfermion': ['quantum'],
  'diraccone': ['quantum'],
  'valleydegeneracy': ['quantum'],
  'fermivelocity': ['electrical'],
  'anomalous': ['quantum'],
  'chiral': ['quantum'],
  'landau': ['quantum'],
  'berry': ['quantum'],
  'shubnikov': ['electrical'],
  'positive': ['photoconductivity'],
  'negative': ['photoconductivity'],
  'tightbinding': ['quantum'],
  'quasiparticle': ['quantum'],
  'anyonic': ['quantum'],
  'fractionalization': ['quantum'],
  'spinorbit': ['spintronic'],
  'hyperfine': ['quantum'],
  'finestructureconstant': ['quantum'],
  'magicangle': ['quantum'],
  'casimir': ['quantum'],
  'quantumdot': ['quantum'],
  'mesoscopic': ['quantum'],
  'spinpumping': ['spintronic'],
  
  // ============= ACTUATORS & SMART MATERIALS =============
  'actuator': ['actuator'],
  'actuation': ['actuator'],
  'muscle': ['actuator', 'muscle'],
  'artificial-muscle': ['actuator', 'muscle'],
  'artificialmuscle': ['muscle'],
  'shape-memory': ['actuator', 'smart'],
  'sma': ['actuator', 'smart'],
  'electroactive': ['actuator', 'electrical'],
  'magnetostrictive': ['actuator'],
  'electrostrictive': ['actuator', 'electrical'],
  'dielectric-elastomer': ['actuator', 'electrical', 'flexible'],
  'ionic': ['actuator'],
  'pneumatic': ['actuator'],
  'hydraulic': ['actuator'],
  'motor': ['actuator', 'electrical'],
  'valve': ['actuator'],
  'switch': ['actuator', 'electrical'],
  'responsive': ['smart', 'sensor'],
  'stimuli-responsive': ['smart', 'sensor'],
  'adaptive': ['smart'],
  'self-healing': ['smart', 'coating'],
  'self-repair': ['smart'],
  'programmable': ['smart'],
  'robot': ['actuator'],
  
  // ============= PROCESSING & MANUFACTURING =============
  'printable': ['coating', 'additive'],
  'printing': ['coating', 'additive'],
  '3d-printing': ['additive'],
  'additive-manufacturing': ['additive'],
  'injection': ['processing'],
  'molding': ['processing'],
  'extrusion': ['processing'],
  'casting': ['processing'],
  'sintering': ['processing'],
  'annealing': ['processing', 'thermal'],
  'tempering': ['processing', 'thermal'],
  'welding': ['processing'],
  'machining': ['processing'],
  'cutting': ['processing'],
  'drilling': ['processing'],
  'grinding': ['processing'],
  'polishing': ['processing', 'surface'],
  'etching': ['processing', 'surface'],
  'lithography': ['processing', 'optical'],
  'sputtering': ['processing', 'coating'],
  'evaporation': ['processing', 'coating'],
  'electroplating': ['processing', 'coating'],
  'electrospinning': ['processing', 'fiber'],
  'sol-gel': ['processing', 'coating'],
  'hydrothermal': ['processing'],
  'solvothermal': ['processing'],
  'microwave-assisted': ['processing'],
  'ultrasonication': ['processing'],
  'ball-milling': ['processing'],
  'calendering': ['processing'],
  'lamination': ['processing', 'composite'],
  'epitaxial': ['growth'],
  
  // ============= ENVIRONMENTAL & SUSTAINABILITY =============
  'environmental': ['environmental'],
  'sustainable': ['sustainable'],
  'recyclable': ['sustainable'],
  'biodegradable': ['sustainable'],
  'compostable': ['sustainable'],
  'renewable': ['sustainable'],
  'green': ['sustainable', 'environmental'],
  'eco-friendly': ['sustainable', 'environmental'],
  'carbon-neutral': ['sustainable', 'environmental'],
  'carbon-capture': ['environmental'],
  'co2-capture': ['environmental'],
  'remediation': ['environmental'],
  'pollution': ['environmental'],
  'wastewater': ['environmental', 'filter'],
  'effluent': ['environmental', 'filter'],
  'emission': ['environmental'],
  'heavy-metal': ['environmental', 'filter'],
  'toxic': ['environmental'],
  'hazardous': ['environmental'],
  'life-cycle': ['sustainable'],
  'lca': ['sustainable'],
  'circular-economy': ['sustainable'],
  'upcycling': ['sustainable'],
  'downcycling': ['sustainable'],
  
  // ============= STRUCTURE & MORPHOLOGY =============
  'structure': ['structure'],
  'crystalline': ['structure'],
  'pentagonheptagon': ['structure'],
  'superlattice': ['structure'],
  'nanoribbon': ['structure'],
  'singlecrystalline': ['structure'],
  'armchair': ['structure'],
  'nanomesh': ['structure'],
  'suspended': ['structure'],
  'supported': ['structure'],
  'nanocoil': ['electrical'],
  'nanowire': ['electrical'],
  
  // ============= SPECIALIZED PROPERTIES =============
  'diamagnetism': ['electrical'],
  'ferromagnetism': ['electrical'],
  'conductivepolymer': ['conductive'],
  'unusually': ['thermal'],
  
  // ============= APPLICATION-SPECIFIC =============
  'automotive': ['composite', 'lightweight'],
  'airplane': ['lightweight', 'strength'],
  'ballistics': ['impact', 'strength'],
  'ballisticarmor': ['strength'],
  'military': ['shielding', 'protection'],
  'helmet': ['impact', 'strength'],
  'tire': ['friction', 'wear'],
  'shoe': ['wear', 'composite'],
  'clothes': ['flexible', 'hydrophobic'],
  'racket': ['strength', 'lightweight'],
  'racquet': ['composite'],
  'trackcar': ['lightweight'],
  'phone': ['flexible']
};
// --- END PASTE ---


let allOntologyTags = []; // Cache for fetched tags

// Function to fetch and cache all tags from Supabase
export async function cacheOntologyTags(supabase) {
  // Check if cache is already populated
  if (allOntologyTags.length > 0) return;
  console.log("Caching ontology tags...");
  try {
      // Fetch only needed fields
      const { data, error } = await supabase.from('ontology_tags').select('id, name, path');
      if (error) throw error; // Throw error to be caught below
      if (data) {
          allOntologyTags = data;
          console.log(`Cached ${allOntologyTags.length} ontology tags.`);
      }
  } catch (err) {
      console.error("Failed to cache ontology tags:", err);
      // Decide how to handle this - maybe retry later?
      // For now, suggestions will just not work if caching fails.
  }
}

// Function to find ontology tag suggestions based on input text
export function findOntologySuggestions(text) {
  if (allOntologyTags.length === 0) {
      console.warn("Ontology tags not cached yet! Cannot provide suggestions.");
      return []; // Return empty array if cache isn't ready
  }
  // Split text into potential keywords, removing punctuation and empty strings
  const words = text.toLowerCase().split(/[\s,.;:!?()/]+/);
  const foundConcepts = new Set(); // Use a Set to store unique concepts found

  // Map keywords from input text to ontology concepts using keywordMap
  words.forEach(word => {
    // Only process words of reasonable length
    if (word.length < 3) return;
    if (keywordMap[word]) {
      keywordMap[word].forEach(concept => foundConcepts.add(concept));
    }
  });

  if (foundConcepts.size === 0) return []; // No relevant concepts found

  const suggestions = [];
  const addedTagIds = new Set(); // Keep track of added tags to avoid duplicates

  // Iterate through cached ontology tags to find matches
  allOntologyTags.forEach(tag => {
    // Extract the last part of the path (the specific tag concept)
    const tagConcepts = tag.path.split('.').pop() || ''; // Handle potential empty path
    // Check against all found concepts
    foundConcepts.forEach(concept => {
      // Check if concept is included in the tag's name or the last part of its path
      if (tag.name.toLowerCase().includes(concept) || tagConcepts.toLowerCase().includes(concept)) {
        // Add suggestion only if it hasn't been added already
        if (!addedTagIds.has(tag.id)) {
             suggestions.push({ id: tag.id, name: tag.name, path: tag.path });
             addedTagIds.add(tag.id); // Mark tag ID as added
        }
      }
    });
  });
  // Sort suggestions alphabetically by name for consistent display
  suggestions.sort((a, b) => a.name.localeCompare(b.name));
  return suggestions;
}